name: CI - Build Test Coverage Sonar

on:
  push:
    branches:
      - main
      - master
      - ci-Tristan
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - ci-Tristan

jobs:
  build:
    name: Build, Test, Coverage, Sonar
    runs-on: ubuntu-latest

    steps:
      # Checkout repository (IMPORTANT for PR analysis)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Setup Gradle cache properly
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70

      # Make gradlew executable
      - name: Grant execute permission
        run: chmod +x ./gradlew

      # Build + Test + Coverage
      - name: Build, Test, Coverage
        run: ./gradlew clean test jacocoTestReport

      # SonarCloud analysis (PR + Branch)
      - name: SonarCloud Scan
        env:
          # Same token since the one in master is also setup by me (Tristan)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew sonar --info

      # Upload JaCoCo report
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/
