name: SonarCloud Check
on:
  push:
    branches:
      - master
      - ci-Alvin
  pull_request:

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Change execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and analyze project coverage
        run: |
          ./gradlew clean test jacocoTestReport

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew sonar --info

      - name: Upload jacoco test report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-test-report
          path: build/reports/jacoco/


